mir_mebeli/cart/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *


urlpatterns = patterns('',
    url(r'^$', 'mir_mebeli.shop.views.get_cart', name='cart'),

    url(r'^add/(?P<product_id>\d+)/$', 'mir_mebeli.shop.views.cart_add_product', name='add_to_cart'),
#    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'mir_mebeli.shop.views.add_to_cart', name='add_to_cart'),

    url(r'^remove/(?P<product_id>\d+)/$', 'mir_mebeli.shop.views.cart_remove_product', name='remove_from_cart'),

    url(r'^qty/set/$', 'mir_mebeli.shop.views.cart_set_product_quantity', name='cart-qty-set-blank'), # url-заготовка для js
    url(r'^qty/set/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'mir_mebeli.shop.views.cart_set_product_quantity',
        name='cart-qty-set'),

    url(r'^qty/inc/(?P<product_id>\d+)/$', 'mir_mebeli.shop.views.cart_inc_or_dec_product_quantity',
        kwargs={'mode': 'inc'}, name='cart-qty-inc'),
    url(r'^qty/dec/(?P<product_id>\d+)/$', 'mir_mebeli.shop.views.cart_inc_or_dec_product_quantity',
        kwargs={'mode': 'dec'}, name='cart-qty-dec'),
)

mir_mebeli/guestbook/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
urlpatterns = patterns('',
    url(r'^$', 'mir_mebeli.guestbook.views.add', name='guestbook-index'),
    url(r'^send/', 'mir_mebeli.guestbook.views.add', name='guestbook-add'),
)

mir_mebeli/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import direct_to_template
from django.http import Http404
from django.conf import settings

from cms.sitemaps.cms_sitemap import CMSSitemap
from cms.apphook_pool import apphook_pool
from cms.views import details

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

try:
    import djapian
    djapian.load_indexes()
except:
    pass

from mir_mebeli.shop.categories import views as cat_views


def anyview(request, *args, **kwargs):
    url_name = kwargs.pop('url_name', None)

    try:
        # try mir_mebeli.shop.categories urls
        if url_name:
            if url_name == 'search':
                return cat_views.search(request)
            elif url_name == 'category_view':
                return cat_views.category(request, **kwargs)
            elif url_name == 'good_view':
                return cat_views.good(request, **kwargs)
    except Http404:
        pass # maybe this is cms url

    cms_kwargs = {'slug': '',}
    if 'slug' not in kwargs and 'category_path' in kwargs:
        cms_kwargs['slug'] = kwargs['category_path']

    # try cms urls
    return details(request, **cms_kwargs)


urlpatterns = patterns('',
    # Example:
    # (r'^mir_mebeli/', include('mir_mebeli.foo.urls')),
    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^robots\.txt$', direct_to_template, {'template': 'robots.txt', 'mimetype': 'text/plain'}),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    (r'^comments/', include('django.contrib.comments.urls')),

    (r'^korzina/', include('mir_mebeli.cart.urls')),

    (r'^wishlist/', include('mir_mebeli.wishlist.urls')),

    url(r'^order/checkout/$', 'mir_mebeli.shop.views.order_checkout', name='shop-order-checkout'),
    url(r'^order/confirm/$', 'mir_mebeli.shop.views.order_confirm', name='shop-order-confirm'),
    url(r'^order/go-bank/(?P<order_id>\d+)$', 'mir_mebeli.shop.views.order_go_bank', name='shop-order-go-bank'),
    url(r'^order/done/(?P<order_id>\d+)/$', 'mir_mebeli.shop.views.order_done', name='shop-order-done'),
    url(r'^order/cancel/(?P<order_id>\d+)/$', 'mir_mebeli.shop.views.order_cancel', name='shop-order-cancel'),
    url(r'^order/info/(?P<order_id>\d+)/$', 'mir_mebeli.shop.views.order_info', name='shop-order-info'),
    url(r'^order/success/$', 'mir_mebeli.shop.views.success_payment', name='shop-order-success'),
    url(r'^order/fail/$', 'mir_mebeli.shop.views.fail_payment', name='shop-order-fail'),
    url(r'^order/noreg/$', 'mir_mebeli.shop.views.order_noreg', name='shop-order-noreg'),

    url(r'^logout/$', 'mir_mebeli.shop.views.logout', name="logout_buyer"),

    url(r'^register-and-login/$', 'mir_mebeli.shop.views.register_and_login', name='register-and-login'),
    url(r'^register-agreement/$', direct_to_template, {'template': 'cms/pages/auth/register_agreement.html'},
        name='register-agreement'),

    # url(r'^req_price/(?P<good_id>\d+)/$', 'mir_mebeli.shop.views.req_price', name="req_price"),
    url(r'^req-phone-call/$', 'mir_mebeli.shop.views.req_phone_call', name="req-phone-call"),

    url(r'^sitemap/$', 'mir_mebeli.sitemap.views.sitemap', name="sitemap"),

    url(r'^profile/edit/$', 'mir_mebeli.shop.views.profile_edit', name='profile-edit'),
    url(r'^change/password/$','mir_mebeli.shop.views.change_password', name='change-password'),

    url(r'^psbank/', include('psbank.urls')),

    # url(r'^korzina/psbank/(?P<order_id>\d+)/$', 'mir_mebeli.shop.views.show_psbank_payment_info',
    #     name='shop-psbank-payment-info'),

    url(r'^api/export-goods/$', 'mir_mebeli.shop.views.export_goods', name='shop-export-goods'),

    url(r'^error/no-buyer-profile/$', login_required(direct_to_template), {'template': 'error/no_buyer_profile.html'},
        name='error_no_buyer_profile'),
    url(r'^yandex-money/', include('yandex_money.urls')),

#    url(r'^', include('cms.urls')),
)


# ссылки каталога и корень cms.
# всё, кроме pages-root, завязано на anyview.
# переменная url_name нужна, чтобы определить какой из паттернов сработал.
cat_urlpatterns = patterns('',
    url(r'^search/$', anyview, kwargs={'url_name': 'search'}, name="search"),

    url(r'^(?P<category_path>.+)/$', anyview, kwargs={'url_name': 'category_view'}, name="category_view"),

    url(r'^(?P<category_path>.+)/(?P<good_id>\d+)\.html$', anyview, kwargs={'url_name': 'good_view'}, name="good_view"),

    # cms
    url(r'^(?P<slug>[0-9A-Za-z-_.//]+)/$', anyview),
    url(r'^$', details, {'slug':''}, name='pages-root'),
)


# подключить ссылки из cms-приложений
if apphook_pool.get_apphooks():
    from cms.appresolver import get_app_patterns
    cat_urlpatterns = get_app_patterns() + cat_urlpatterns


urlpatterns += cat_urlpatterns

if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ) + urlpatterns

mir_mebeli/wishlist/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *


urlpatterns = patterns('mir_mebeli.wishlist.views',
    url(r'^$', 'wishlist', name='wishlist'),
    url(r'^print/$', 'wishlist_print', name='wishlist_print'),
    url(r'^add/(?P<product_id>\d+)/$', 'add_product', name='add_to_wishlist'),
    url(r'^remove/(?P<product_id>\d+)/$', 'remove_product', name='remove_from_wishlist'),
)

mir_mebeli/guestbook/models.py
# -*- coding: utf-8 -*-

from django.db import models

# from basic.people.models import Person

class Message(models.Model):
    STATUS_CHOICES = (
        ('P', u'Опубликовано'),
        ('N', u'Не опубликовано'),
    )
    status = models.CharField(u"статус", max_length=1, choices=STATUS_CHOICES, default='P')
    fio = models.CharField(u"автор", max_length=100)
    email = models.CharField(u"e–mail", max_length=30)
    text = models.TextField(u"текст", blank=True, null=True)
    created = models.DateTimeField(u"добавлено", auto_now_add=True)

    def __unicode__(self):
        return u'%s (%s)' % (self.fio, self.status)
    
    class Meta:
        verbose_name = u'сообщение'
        verbose_name_plural = u'сообщения гостевой'

mir_mebeli/sitemap/models.py
from django.db import models

# Create your models here.

mir_mebeli/vacancies/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.urlresolvers import reverse
import mptt

# Create your models here.

class Vacancy(models.Model):
    GENDER_CHOICES = (
        ('M', u'Мужчина'),
        ('F', u'Женщина'),
    )   
    position = models.CharField(u"должность", max_length = 50)
    slug = models.SlugField(editable=False, blank=True, null=True)
    salary = models.CharField(u"оклад", max_length = 50)
    age = models.CharField(u"возраст", max_length = 30, blank=True, null=True)
    gender = models.CharField(u"пол", max_length = 1, choices = GENDER_CHOICES, blank=True, null=True)
    education = models.CharField(u"образование", max_length = 50)
    experience = models.CharField(u"опыт работы", max_length = 50)
    schedule = models.CharField(u"график работы", max_length = 50, blank=True, null=True)
    acting = models.TextField(u"основные обязанности", blank=True, null=True)
    skill = models.TextField(u"требования к кандидату", blank=True, null=True)
    contact = models.TextField(u"контактное лицо", blank=True, null=True)
    count_view = models.PositiveIntegerField(u"кол-во просмотров", default = 0, editable=False)
    close = models.BooleanField(u"вакансия закрыта", default = False)
    
    def __unicode__(self):
        return u"%s" % self.position
    
    def save(self):
        from pytils.translit import slugify
        self.slug = slugify(self.position)
        super(Vacancy, self).save()
    
    def get_parent(self):
      return None
    def set_parent(self, parent):
      pass

    parent = property(get_parent, set_parent)

    def get_parent_id(self):
      return None
    def set_parent_id(self, parent):
      pass

    parent_id = property(get_parent_id, set_parent_id)
    
    def get_menu_title(self):
        return self.position

    def get_absolute_url(self):
        return reverse('vacancy_view', kwargs={'vacancy':self.slug})
    
    class Meta:
        verbose_name = u"вакансия"
        verbose_name_plural = u"вакансии"
        
try:
    mptt.register(Vacancy)
except mptt.AlreadyRegistered:
    pass

mir_mebeli/cart/views.py
# Create your views here.

mir_mebeli/guestbook/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.views.generic.simple import direct_to_template
from django.conf import settings

from mir_mebeli.guestbook.models import Message
from mir_mebeli.shop.forms import MessageForm
from mir_mebeli.shop.models import get_manager_emails
from mir_mebeli.utilities.my_pagination import _paginate


SHOP_SETTINGS = getattr(settings, 'SHOP_SETTINGS')


def add(request):
    if request.POST:
        form = MessageForm(request.POST)

        if form.is_valid() and form.cleaned_data['phone']:
            return HttpResponseRedirect(reverse('guestbook-index'))

        if form.is_valid() and not form.cleaned_data['phone']:
            message = Message(
                fio = form.cleaned_data['fio'],
                email = form.cleaned_data['email'],
                text = form.cleaned_data['text']
            )
            message.save()

            subject = u'Добавлено новое сообщение в гостевую книгу сайта sklad51.ru'
            email_msg = render_to_string('mail/message.txt', {'msg': message,})
            email_sender = SHOP_SETTINGS['EMAIL_SENDER']
            recipients = get_manager_emails()

            send_mail(subject, email_msg, email_sender, recipients, fail_silently=True)

            return HttpResponseRedirect(reverse('guestbook-index'))
    else:
        form = MessageForm()

    messages = Message.objects.filter(status="P").order_by("-created") # only published messages

    extra_context = {
        "form": form,
        'pagination_form_text': u'Вывести по',
    }
    extra_context.update(_paginate(request, messages))

    return direct_to_template(request, 'cms/pages/guestbook.html', extra_context)

mir_mebeli/shop/categories/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404
from django.views.generic.simple import direct_to_template
from django.views.decorators.http import require_GET
from django.core.urlresolvers import reverse
from django.http import Http404

from mir_mebeli.shop.models import Category, Good
from mir_mebeli.shop.forms import SearchForm
from mir_mebeli.utilities.my_pagination import _paginate


def _catalog_breadcrumb(request, category, include_self=True):
    """Breadcrumbs для текущей категории каталога."""
    ancestors = [{'url': '/', 'title': u'Каталог строительных материалов'}]
    ancestors += [{'url': cat.get_absolute_url(), 'title': cat.name} for cat in category.get_ancestors()]
    if include_self:
        ancestors.append({'url': category.get_absolute_url(), 'title': category.name})
    return {'catalog_breadcrumb': ancestors}


def category(request, category_path=None):
    """Все товары внутри категории и в её подкатегориях.
    """
    category = get_object_or_404(Category, path=category_path, hidden=False)

    _sub_categories = category.get_descendants().filter(hidden=False).order_by('order', 'name')
    _category_ids = [_cat.pk for _cat in _sub_categories]
    _category_ids.append(category.pk)

    goods_list = (Good.objects.filter(is_available=True).filter(category__in=_category_ids)
        .extra(select={'ordering_name': "CASE WHEN display_name <> '' THEN display_name ELSE name END"})
        .order_by('ordering_name')
    )

    root_category = category.get_root()
    root_sub_categories = root_category.get_descendants().filter(count_all__gt=0).filter(hidden=False).order_by('order', 'name')

    extra_context = {
        'category': category,
        'goods_list': goods_list,
        'root_category': root_category,
        'root_sub_categories': root_sub_categories,
    }

    if request.is_ajax():
        template = 'cms/pages/goods_list.html'
    else:
        template = 'cms/pages/category.html'
        extra_context.update(_catalog_breadcrumb(request, category))

    return direct_to_template(request, template, extra_context)


def good(request, category_path=None, good_id=None):
    """Товар."""
    category = get_object_or_404(Category, path=category_path)
    good = get_object_or_404(category.goods, id=good_id)

    def _get_root_category():
        root_category = category
        if not root_category.basic:
            cat_parents = category.get_ancestors().filter(basic=True)
            if cat_parents and cat_parents[0]:
                root_category = cat_parents[0]
        return root_category

    root_category = _get_root_category()

    extra_context = {
        'category': category,
        'good': good,
        'root_category': root_category,
    }

    # если category подрубрика, то взять все товары внутри нее
    sub_category_goods = None
    if not category.basic:
        sub_category_goods = category.goods.all().order_by('name')

    try:
        sub_category_goods_index = [index for index, x in enumerate(sub_category_goods, start=1) if x.pk == good.pk][0]
    except (ValueError, IndexError, TypeError) as e:
        sub_category_goods_index = None

    extra_context['sub_category_goods'] = sub_category_goods
    extra_context['sub_category_goods_index'] = sub_category_goods_index
    #extra_context.update(_catalog_breadcrumb(request, category, include_self=True))
    return direct_to_template(request, 'cms/pages/good_popup.html', extra_context)


@require_GET
def search(request):
    search_form = SearchForm(data=request.GET)
    extra_context = {'search_form': search_form,}

    if search_form.is_valid():
        query = search_form.cleaned_data.get('q')
        cat = search_form.cleaned_data.get('cat')

        try:
            category = Category.objects.get(pk=int(cat))
        except (TypeError, ValueError, Category.DoesNotExist):
            category = None

        if cat:
            results = Good.indexer.search(u'%s AND "%s"' % (query, cat.name,)).prefetch().spell_correction()
        else:
            results = Good.indexer.search(query).prefetch().spell_correction()

        extra_context['category'] = category
        extra_context['total_found'] = len(results)
        extra_context['maybe'] = results.get_corrected_query_string()
        extra_context.update(_paginate(request, results))

    return direct_to_template(request, 'cms/pages/search.html', extra_context)

mir_mebeli/sitemap/views.py
# -*- coding: utf-8 -*-
from django.views.generic.simple import direct_to_template

from cms.sitemaps import CMSSitemap


def sitemap(request):
    extra_context = {
        'cms_sitemap': CMSSitemap(),
    }
    return direct_to_template(request, 'cms/pages/sitemap.html', extra_context)

mir_mebeli/vacancies/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404

from cms.utils import auto_render

from mir_mebeli.vacancies.models import Vacancy


@auto_render
def root(request):
    vacancies = Vacancy.objects.filter(close=False)
    return 'cms/pages/vacancies.html', {'vacancies': vacancies}


@auto_render
def vacancy(request, vacancy=None):
    vacancy = get_object_or_404(Vacancy, slug=vacancy, close=False)
    is_first_view = request.session.get('first_view_%s' % vacancy.pk, True)
    if is_first_view:
        vacancy.count_view += 1
        vacancy.save()
        request.session['first_view_%s' % vacancy.pk] = False
    return 'cms/pages/vacancy.html', {'vacancy': vacancy}

mir_mebeli/templates/cms/pages/contacts.html
{% extends "cms/base.html" %}

{% load cms_tags %}

{% block content %}
    {% include "block_cart.html" %}

    {% placeholder "content" %}

    <div id="ymaps-map-id_1345400191829580153800-contacts" class="yandex-map-container"><script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Adabc022f5f1a8c89e32d7130dab8560ff19ad1442098fa5260d0af3a760953d2&amp;width=1200&amp;height=450&amp;lang=ru_RU&amp;scroll=true"></script>
	</div>
    
{% endblock %}

mir_mebeli/templates/cms/pages/good_popup.html
{% load shop cart_tags thumbnail %}

<div class="good-popup-wrapper">
    <div class="pseudo-header-category"><div class="title">{{ good.get_name }}</div></div>
    {% if good.price > 0 %}<div class="price">{{ good.price|price }} р.</div>{% endif %}
    <div class="image">
        {% thumbnail good.image "300x300" padding=True as img %}
            <img src="{{ img.url }}" width="300" height="300" title="{{ good.get_name }}" />
        {% empty %}
            <img src="{{ MEDIA_URL }}images/noimage.jpg" width="300" height="300" title="{{ good.get_name }}" />
        {% endthumbnail %}
    </div>

    <div class="desc">
        {% with good.get_custom_fields as custom_fields %}
            {% if custom_fields %}
                <div class="custom-fields">
                    {% for f in custom_fields.itervalues %}
                        {% if f.value %}
                            <div>
                                {{ f.name }}: {{ f.value }}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}

        {{ good.short_description|linebreaks }}

        {{ good.description|linebreaks }}
    </div>

    <div class="popup_bottom">
      <div class="quantity">Количество: {% cart_set_quantity good cart 1 %}</div>

      <div class="link">{% add_to_cart_link good cart 'В корзине' 'В корзину' %}</div>
    </div>
</div>

mir_mebeli/templates/cms/pages/order_done.html
{% extends 'cms/base.html' %}

{% load shop pytils_numeral %}

{% block title %}Спасибо за ваш заказ!{% endblock %}

{% block content %}

{# Шаг 3 -- Результат заказа #}

<h2>Спасибо за ваш заказ!</h2>

<div style="background: #fff;">
    <div class="blue-border p20">
        <p style="line-height: 200%;">
            {# если оплата карточкой #}
            {% if order.is_card_payment %}
                {% if order.is_paid and order.is_psbank_payment %}
                    {# при успешной оплате #}
                    Оплата прошла успешно, Ваш заказ принят.<br />
                    В ближайшее время с Вами свяжется наш менеджер, чтобы сообщить о доставке заказанных Вами товаров.<br />
                    О ходе выполнения Вашего заказа Вы всегда можете узнать в своей корзине, на вкладке <a href="{% url cart %}#orders">"Мои заказы"</a>.
                {% else %}
                    {% if order.is_await_approval_status %}
                        {# заказ ожидает проверки менеджером #}
                        Спасибо за Ваш заказ!
                        В самое ближайшее время наш менеджер проверит наличие заказанных вами товаров на складе, забронирует их для Вас и Вы сможете перейти к оплате.
                        Ссылка на страницу оплаты будет отправлена Вам на адрес электронной почты, который Вы указывали при регистрации на сайте: {{ request.user.email }}
                    {% else %}
                        {# вероятно, оплата не прошла #}
                        Оплата не прошла.<br />
                        Возникли какие-то сложности с оплатой, но мы всё равно приняли Ваш заказ.<br />
                        В ближайшее время с Вами свяжется наш менеджер, чтобы помочь Вам, если у Вас возникли какие-то трудности.<br />
                        Вы всегда можете повторно попробовать оплатить заказ в своей корзине, на вкладке <a href="{% url cart %}#orders">"Мои заказы"</a>.
                    {% endif %}
                {% endif %}
            {% endif %}

            {# если оплата наличными #}
            {% if order.is_cash_payment %}
                {% if order.is_unpaid %}
                    Ваш заказ принят.<br />
                    В ближайшее время с Вами свяжется наш менеджер, чтобы договориться о том, где Вы сможете оплатить товар и согласовать с Вами дату его доставки.<br />
                    О ходе выполнения Вашего заказа Вы всегда можете узнать в своей корзине, на вкладке <a href="{% url cart %}#orders">"Мои заказы"</a>.
                {% else %}
                    Статус заказа: {{ order.get_status_display }}.
                {% endif %}
            {% endif %}
        </p>
        <p><a href="{% url cart %}#orders">Мои заказы</a> | <a href="/">Главная страница магазина</a></p>
    </div>
</div>

{% endblock %}

mir_mebeli/templates/cms/pages/order_info.html
{% extends 'cms/base.html' %}

{% load shop pytils_numeral thumbnail %}

{% block title %}Информация о заказе № {{ order.pk }}{% endblock %}

{# информация о заказе #}

{% block content %}

<div><a href="{% url cart %}#orders">Вернуться в корзину</a></div>

<div id="order_{{ order.pk }}" class="cart-order">
    {% if message %}
    <h2>
        {{ message }}
    </h2>
    {% endif %}
    <div class="order-title">
        Заказ №{{ order.pk }} от {{ order.create_date|date:"d.m.Y" }}
    </div>

    <div class="tbl-header">
        <div class="l w540">Состав заказа</div>
        <div class="l w110">Количество</div>
        <div class="l w85">Цена</div>
        <div class="r w400">Параметры заказа</div>
    </div>

    <div class="l w750">
        {% for item in order.items.all %}
            {% with item.good as good %}
                <div class="clear order-good no-borders{% cycle ' odd' ' even' %}">
                    <div class="image l">
                        {% thumbnail good.image "100x70" padding=True as img %}
                            <img src="{{ img.url }}" width="100" height="70" title="{{ good.get_name }}" />
                        {% empty %}
                            <img src="{{ MEDIA_URL }}images/noimage.jpg" width="100" height="70" title="{{ good.get_name }}" />
                        {% endthumbnail %}
                    </div>
                    <div class="l w400 mr20">
                        <div class="title"><a href="{{ good.get_absolute_url }}">{{ good.get_name }}</a></div>
                        <div class="desc">
                            {% if good.dims %}<p title="Длина / Высота / Ширина (мм)">{{ good.dims }}</p>{% else %}<p>нет размеров</p>{% endif %}
                        </div>
                    </div>
                    <div class="l w110 price"><span class="pprice2">{{ item.count }}</span></div>
                    <div class="l w85 price"><span class="pprice2">{{ item.price|price }} р.</span></div>
                </div>
            {% endwith %}
        {% endfor %}
    </div>

    <div class="order-param">
        <div>Продавец: ООО "Торговый дом, 183031, Мурманск, Свердлова 29/2</div>

        <div style="margin-top: 10px;">Покупатель: {{ order.get_full_fio|default:"нет данных" }}</div>
        <div>Адрес для доставки: {{ order.city }}, {{ order.address }}</div>
        <div>Телефон покупателя: {{ order.phone }}</div>

        <div style="margin-top: 10px;">
            Оплата товаров:<br />
            {{ order.get_payment_method }} &ndash;
            <span class="pprice2">{{ order.sum|price }} р.</span>
        </div>

        <div style="margin-top: 10px;">
            Статус заказа:<br />
            {{ order.get_status_display|capfirst }} {% if order.is_done %}{{ order.done_date|date:"d.m.Y" }}{% else %}{% if order.is_canceled %}{{ order.cancel_date|date:"d.m.Y" }}{% endif %}{% endif %}
        </div>
    </div>
</div>

{% endblock %}

mir_mebeli/templates/cms/pages/vacancy.html
{% extends 'cms/base.html' %}

{% load menu_tags %}

{% block page-title %}{{ vacancy.position }}{% endblock %}

{% block cart %}<h5>Кол-во просмотров: {{ vacancy.count_view }}</h5>{% endblock %}

{% block content_class %}class="narrow"{% endblock %}

{% block sidebar %}
<div id="sidebar">
    {% show_menu_below_id "company" 0 100 100 100 "cms/menu/about_menu.html" %}
</div>
{% endblock %}

{% block content %}
    <div class="vacancy">
        <table>
            <tr>
                <th>Зарплата</th>
                <th>Образование</th>
                <th>Опыт работы</th>
            </tr>
            <tr>
                <td>{{ vacancy.salary }}</td>
                <td>{{ vacancy.education }}</td>
                <td>{{ vacancy.experience }}</td>
            </tr>
            {% if vacancy.gender or vacancy.age or vacancy.skills %}
                <tr>
                    <th colspan="3">Требования к кандидату</th>
                </tr>
                {% if vacancy.gender or vacancy.age %}
                    <tr>
                        <td colspan="3">
                            {% if vacancy.gender %}{{ vacancy.get_gender_display }}{% endif %}
                            {% if vacancy.age %}{{ vacancy.age }}{% endif %}
                        </td>
                    </tr>
                {% endif %}
                {% if vacancy.skill %}
                    <tr>
                        <td colspan="3">{{ vacancy.skill|linebreaksbr }}</td>
                    </tr>
                {% endif %}
            {% endif %}
            {% if vacancy.acting %}
                <tr>
                    <th colspan="3">Основные обязанности</th>
                </tr>
                <tr>
                    <td colspan="3">{{ vacancy.acting|linebreaksbr }}</td>
                </tr>
            {% endif %}
            {% if vacancy.schedule %}
                <tr>
                    <th colspan="3">График работы</th>
                </tr>
                <tr>
                    <td colspan="3">{{ vacancy.schedule }}</td>
                </tr>
            {% endif %}
            {% if vacancy.contact %}
                <tr>
                    <th colspan="3">Контактное лицо</th>
                </tr>
                <tr>
                    <td colspan="3">{{ vacancy.contact|linebreaksbr }}</td>
                </tr>
            {% endif %}
        </table>
    </div>
{% endblock %}